# Generated by Django 4.2.6 on 2023-11-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewerapp', '0002_remove_convert_filepath_convert_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convert',
            name='mp3FilePath',
            field=models.CharField(default='', max_length=200),
        ),
    ]
